# Generated by Django 5.1.3 on 2024-12-02 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mus', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
        migrations.AlterField(
            model_name='history',
            name='last_time',
            field=models.IntegerField(),
        ),
    ]
