# Generated by Django 5.1.3 on 2024-12-02 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mus', '0002_delete_avatar_alter_history_last_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('avatar', models.ImageField(upload_to='avatars/')),
            ],
        ),
    ]
