# Generated by Django 5.1.3 on 2024-12-02 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mus', '0003_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='songinfo',
            name='song_singer_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
