# Generated by Django 5.1.3 on 2024-12-02 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mus', '0004_songinfo_song_singer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songinfo',
            name='song_name',
            field=models.CharField(max_length=64),
        ),
    ]
