# Generated by Django 5.1.3 on 2024-12-02 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mus', '0005_alter_songinfo_song_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songinfo',
            name='song_singer',
            field=models.CharField(max_length=32),
        ),
    ]
